//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CONTACTO
    {
        public int ID_contacto { get; set; }
        [Required(ErrorMessage ="EL NOMBRE ES REQUERIDO")]
        public string nombre { get; set; }
        [Required(ErrorMessage ="EL NUMERO TELEFONICO ES REQUERIDO")]
        public string celular { get; set; }
        [Required(ErrorMessage ="EL EMAIL ES REQUERIDO")]

        public string email { get; set; }
        [Required(ErrorMessage ="LA DIRECCION ES REQUERIDA")]
        public string direccion { get; set; }
    }
}
