//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATERIA()
        {
            this.ESTUDIANTES_MATERIAS = new HashSet<ESTUDIANTES_MATERIAS>();
        }
    
        public int ID_materia { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string horario { get; set; }
        public Nullable<int> creditos { get; set; }
        public string profesor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTUDIANTES_MATERIAS> ESTUDIANTES_MATERIAS { get; set; }
    }
}
