//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UTILITIES_APPEntities : DbContext
    {
        public UTILITIES_APPEntities()
            : base("name=UTILITIES_APPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONTACTO> CONTACTOes { get; set; }
        public virtual DbSet<ESTUDIANTE> ESTUDIANTES { get; set; }
        public virtual DbSet<ESTUDIANTES_MATERIAS> ESTUDIANTES_MATERIAS { get; set; }
        public virtual DbSet<EVENTO> EVENTOS { get; set; }
        public virtual DbSet<MATERIA> MATERIAS { get; set; }
    }
}
